### ISSUE TITLE
I have problem that I can't described

### ISSUE THREAD

**Issue by pojii** [BuildingXwithJS/elasticsearch-tutorial#1]
[https://pastebin.com/PLjGwZ8V](url)

this is logs 

this is problem capture
<img width="411" alt="Screen Shot 2563-03-15 at 19 23 08" src="https://user-images.githubusercontent.com/13790806/76701343-f4004a80-66f2-11ea-9e57-6dd1001aa95f.png">

I tried to google it but not work. Could anyone help me? Thank you.

**Comment by pojii** [comment]
another logs 
`elasticsearch_1   | [2020-03-15T12:13:05,365][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1   | [2020-03-15T12:13:05,616][INFO ][o.e.e.NodeEnvironment    ] [Nys_1ng] using [1] data paths, mounts [[/ (overlay)]], net usable_space [51.8gb], net total_space [58.4gb], types [overlay]
elasticsearch_1   | [2020-03-15T12:13:05,617][INFO ][o.e.e.NodeEnvironment    ] [Nys_1ng] heap size [990.7mb], compressed ordinary object pointers [true]
elasticsearch_1   | [2020-03-15T12:13:05,620][INFO ][o.e.n.Node               ] node name [Nys_1ng] derived from node ID [Nys_1ng2T7a9mW_gAYXoCg]; set [node.name] to override
elasticsearch_1   | [2020-03-15T12:13:05,624][INFO ][o.e.n.Node               ] version[6.0.0], pid[1], build[8f0685b/2017-11-10T18:41:22.859Z], OS[Linux/4.19.76-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_151/25.151-b12]
elasticsearch_1   | [2020-03-15T12:13:05,625][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config]
elasticsearch_1   | [2020-03-15T12:13:10,686][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [aggs-matrix-stats]
elasticsearch_1   | [2020-03-15T12:13:10,686][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [analysis-common]
elasticsearch_1   | [2020-03-15T12:13:10,686][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [ingest-common]
elasticsearch_1   | [2020-03-15T12:13:10,690][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [lang-expression]
elasticsearch_1   | [2020-03-15T12:13:10,691][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [lang-mustache]
elasticsearch_1   | [2020-03-15T12:13:10,691][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [lang-painless]
elasticsearch_1   | [2020-03-15T12:13:10,691][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [parent-join]
elasticsearch_1   | [2020-03-15T12:13:10,692][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [percolator]
elasticsearch_1   | [2020-03-15T12:13:10,692][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [reindex]
elasticsearch_1   | [2020-03-15T12:13:10,693][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [repository-url]
elasticsearch_1   | [2020-03-15T12:13:10,693][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [transport-netty4]
elasticsearch_1   | [2020-03-15T12:13:10,693][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded module [tribe]
elasticsearch_1   | [2020-03-15T12:13:10,696][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded plugin [ingest-geoip]
elasticsearch_1   | [2020-03-15T12:13:10,696][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded plugin [ingest-user-agent]
elasticsearch_1   | [2020-03-15T12:13:10,696][INFO ][o.e.p.PluginsService     ] [Nys_1ng] loaded plugin [x-pack]
elasticsearch_1   | [2020-03-15T12:13:26,781][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/141] [Main.cc@128] controller (64 bit): Version 6.0.0 (Build 8e6ab35cf803a2) Copyright (c) 2017 Elasticsearch BV
elasticsearch_1   | [2020-03-15T12:13:27,117][INFO ][o.e.d.DiscoveryModule    ] [Nys_1ng] using discovery type [zen]
elasticsearch_1   | [2020-03-15T12:13:31,125][INFO ][o.e.n.Node               ] initialized
elasticsearch_1   | [2020-03-15T12:13:31,125][INFO ][o.e.n.Node               ] [Nys_1ng] starting ...
elasticsearch_1   | [2020-03-15T12:13:31,827][INFO ][o.e.t.TransportService   ] [Nys_1ng] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
elasticsearch_1   | [2020-03-15T12:13:33,208][INFO ][o.e.m.j.JvmGcMonitorService] [Nys_1ng] [gc][young][2][3] duration [940ms], collections [1]/[1s], total [940ms]/[1.4s], memory [293.5mb]->[51.5mb]/[990.7mb], all_pools {[young] [259.3mb]->[2.6mb]/[266.2mb]}{[survivor] [26.4mb]->[33.2mb]/[33.2mb]}{[old] [7.8mb]->[15.6mb]/[691.2mb]}
elasticsearch_1   | [2020-03-15T12:13:33,209][WARN ][o.e.m.j.JvmGcMonitorService] [Nys_1ng] [gc][2] overhead, spent [940ms] collecting in the last [1s]
elasticsearch_1   | [2020-03-15T12:13:35,321][INFO ][o.e.c.s.MasterService    ] [Nys_1ng] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {Nys_1ng}{Nys_1ng2T7a9mW_gAYXoCg}{FscBxXMOQ1aUwP0erPLOUA}{127.0.0.1}{127.0.0.1:9300}{ml.max_open_jobs=10, ml.enabled=true}
elasticsearch_1   | [2020-03-15T12:13:35,377][INFO ][o.e.c.s.ClusterApplierService] [Nys_1ng] new_master {Nys_1ng}{Nys_1ng2T7a9mW_gAYXoCg}{FscBxXMOQ1aUwP0erPLOUA}{127.0.0.1}{127.0.0.1:9300}{ml.max_open_jobs=10, ml.enabled=true}, reason: apply cluster state (from master [master {Nys_1ng}{Nys_1ng2T7a9mW_gAYXoCg}{FscBxXMOQ1aUwP0erPLOUA}{127.0.0.1}{127.0.0.1:9300}{ml.max_open_jobs=10, ml.enabled=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
elasticsearch_1   | [2020-03-15T12:13:35,502][INFO ][o.e.h.n.Netty4HttpServerTransport] [Nys_1ng] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1   | [2020-03-15T12:13:35,502][INFO ][o.e.n.Node               ] [Nys_1ng] started
elasticsearch_1   | [2020-03-15T12:13:36,868][INFO ][o.e.g.GatewayService     ] [Nys_1ng] recovered [0] indices into cluster_state`

**Comment by yamalight** [comment]
@pojii seems like your elasticsearch instance is unreachable

**Comment by pojii** [comment]
> @pojii seems like your elasticsearch instance is unreachable

Thank you very much.
